import { Lexend } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/ReduxProvider";

const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.className} ${lexend.variable}`}>
        <ReduxProvider>
          <main className="max-w-[1440px] mx-auto flex h-screen overflow-y-scroll font-lexend">
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
